id: ABC86DC55
title: CXIII_§260F. ṣaṣṭhaṃ daśakam
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.336919
  last_modified_at: 2022-03-02 00:08:58.336923
