id: ABC86DC55
title: CXI_§206. lta ba sna tshogs kyi miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.896396
  last_modified_at: 2022-03-02 00:08:58.896401
