id: ABC86DC55
title: CXI_§217. aṣṭādaśavidyā sthānāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.966393
  last_modified_at: 2022-03-02 00:08:58.966396
