id: ABC86DC55
title: CXIV_§279. gos kyi gźi’i miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.810803
  last_modified_at: 2022-03-02 00:08:58.810807
