id: ABC86DC55
title: CXI_§204. bye brag pa’i tshig gi don drug la sogs pa’i miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.889974
  last_modified_at: 2022-03-02 00:08:58.889980
