id: ABC86DC55
title: CVI_§117. catvāro yonayaḥ
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.667266
  last_modified_at: 2022-03-02 00:08:57.667269
