id: ABC86DC55
title: CX_§188. catvāro varṇāḥ
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:59.090841
  last_modified_at: 2022-03-02 00:08:59.090848
