id: ABC86DC55
title: CVIII_§159. bsam gtan gñis pa’i sa’i miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.379821
  last_modified_at: 2022-03-02 00:08:57.379826
