id: ABC86DC55
title: CXIII_§243. puṣpaguṇanāmāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.812415
  last_modified_at: 2022-03-02 00:08:57.812422
