id: ABC86DC55
title: CXIV_§280. ’dul ba las bstus pa’i skad thor bu pa
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.851207
  last_modified_at: 2022-03-02 00:08:58.851214
