id: ABC86DC55
title: CI_§11. trīṇy āvenikāni smṛtyupasthānāni nāmāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.176034
  last_modified_at: 2022-03-02 00:08:57.176038
