id: ABC86DC55
title: CIII_§60. indriyavaimātratā
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:56.840917
  last_modified_at: 2022-03-02 00:08:56.840920
