id: ABC86DC55
title: CIX_§176. kuṃbhāṇḍanāmāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.126770
  last_modified_at: 2022-03-02 00:08:57.126774
