id: ABC86DC55
title: CIII_§42. pañcabalāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:56.772014
  last_modified_at: 2022-03-02 00:08:56.772017
