id: ABC86DC55
title: CIX_§180. ṣaṭ śāstāraḥ
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.151514
  last_modified_at: 2022-03-02 00:08:57.151518
