id: ABC86DC55
title: CVII_§138. kuśalādayaḥ
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.539383
  last_modified_at: 2022-03-02 00:08:57.539388
