id: ABC86DC55
title: CII_§38. catvāri smṛtyupasthānanāmāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:56.951710
  last_modified_at: 2022-03-02 00:08:56.951712
