id: ABC86DC55
title: CIV_§76. pañcavidyāsthānāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.042888
  last_modified_at: 2022-03-02 00:08:57.042892
