id: ABC86DC55
title: CXIII_§251. rdul phra mo las bsgyur te dpag tshad la sogs par bsgre ba’i miṅ
  la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.256368
  last_modified_at: 2022-03-02 00:08:58.256375
