id: ABC86DC55
title: CIX_§161. bsam gtan bźi pa’i sa’i miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.054068
  last_modified_at: 2022-03-02 00:08:57.054071
