id: ABC86DC55
title: CVI_§116. pañcaphalāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.664821
  last_modified_at: 2022-03-02 00:08:57.664825
