id: ABC86DC55
title: CIV_§73. trīṇi vimokṣamukhāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.037121
  last_modified_at: 2022-03-02 00:08:57.037123
