id: ABC86DC55
title: CXII_§231. źo mar daṅ zas skom gyi miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.527760
  last_modified_at: 2022-03-02 00:08:58.527767
