id: ABC86DC55
title: CX_§189. pha ma la sogs pa gñen bśes kyi miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:59.099671
  last_modified_at: 2022-03-02 00:08:59.099677
