id: ABC86DC55
title: CIV_§71. aṣṭāv abhibhvāyatanāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.032498
  last_modified_at: 2022-03-02 00:08:57.032501
