id: ABC86DC55
title: CXII_§234. pariṣkāranāmāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.576479
  last_modified_at: 2022-03-02 00:08:58.576485
