id: ABC86DC55
title: CXIV_§276. chu ruṅ ba rnam pa lṅa’i miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.794479
  last_modified_at: 2022-03-02 00:08:58.794483
