id: ABC86DC55
title: CVI_§120. aṣṭa_avakṣaṇāḥ
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.676360
  last_modified_at: 2022-03-02 00:08:57.676365
