id: ABC86DC55
title: CI_§16. trīṇi prātihāryāṇi
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.191580
  last_modified_at: 2022-03-02 00:08:57.191584
