id: ABC86DC55
title: CI_§4. asamasamapañcaskandhaḥ
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.277305
  last_modified_at: 2022-03-02 00:08:57.277310
