id: ABC86DC55
title: CX_§194. rgas pa daṅ na ba’i miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:59.139850
  last_modified_at: 2022-03-02 00:08:59.139856
