id: ABC86DC55
title: CVI_§115. catvāraḥ pratyayāḥ
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.662648
  last_modified_at: 2022-03-02 00:08:57.662652
