id: ABC86DC55
title: CXIV_§277. dge sbyoṅ gi skyon du brtsi ba la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.799732
  last_modified_at: 2022-03-02 00:08:58.799736
