id: ABC86DC55
title: CXI_§218. bzo’i gnas daṅ sgyu rtsal gyi miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.974383
  last_modified_at: 2022-03-02 00:08:58.974388
