id: ABC86DC55
title: CXI_§205. tshad ma maṅ po smra ba las ’byuṅ ba
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.893280
  last_modified_at: 2022-03-02 00:08:58.893286
