id: ABC86DC55
title: CXIII_§256. ltuṅ byed sde lṅa daṅ ma ṅes pa’i miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.296394
  last_modified_at: 2022-03-02 00:08:58.296399
