id: ABC86DC55
title: CXIII_§252. stobs bcur bsgur te bsgre ba’i miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.259907
  last_modified_at: 2022-03-02 00:08:58.259912
