id: ABC86DC55
title: CXI_ยง213
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.952575
  last_modified_at: 2022-03-02 00:08:58.952581
