id: ABC86DC55
title: CXI_§212. yi dags su gtogs pa’i miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.929814
  last_modified_at: 2022-03-02 00:08:58.929817
