id: ABC86DC55
title: CIII_§41. pañcendriyāṇi
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:56.769963
  last_modified_at: 2022-03-02 00:08:56.769967
