id: ABC86DC55
title: CXII_§236. maṇiratnanāmāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.595976
  last_modified_at: 2022-03-02 00:08:58.595982
