id: ABC86DC55
title: CXII_§224. skad go mthun gyi miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.424281
  last_modified_at: 2022-03-02 00:08:58.424288
