id: ABC86DC55
title: CXIV_§268. catvārah śramaṇakārakadharmāḥ
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.685888
  last_modified_at: 2022-03-02 00:08:58.685905
