id: ABC86DC55
title: CXIII_§249. abhdharmodbhavitasaṃkhyānāmāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.212397
  last_modified_at: 2022-03-02 00:08:58.212402
