id: ABC86DC55
title: CV_§98. spro źiṅ brtson pa la sogs pa’i miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.760695
  last_modified_at: 2022-03-02 00:08:57.760703
