id: ABC86DC55
title: CXII_§239. go mtshon gyi miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.625945
  last_modified_at: 2022-03-02 00:08:58.625951
