id: ABC86DC55
title: CXIII_§257. phas pham pa bźi’i miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.298650
  last_modified_at: 2022-03-02 00:08:58.298654
