id: ABC86DC55
title: CIV_§63. dharmaparyāyaḥ
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:56.969075
  last_modified_at: 2022-03-02 00:08:56.969078
