id: ABC86DC55
title: CXIV_§271. yo byad bcu gsum gyi miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.747816
  last_modified_at: 2022-03-02 00:08:58.747822
