id: ABC86DC55
title: CVI_§114. ṣaḍ hetavaḥ
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.659976
  last_modified_at: 2022-03-02 00:08:57.659982
