id: ABC86DC55
title: CI_§19. sūtrāntoddhṛtāni tathāgatamāhātmyanāmāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.247517
  last_modified_at: 2022-03-02 00:08:57.247523
