id: ABC86DC55
title: CVIII_§156. khams gsum gyi rim pa’i miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.369939
  last_modified_at: 2022-03-02 00:08:57.369943
