id: ABC86DC55
title: CII_§22. bodhisatvānāṃ sādhāraṇanāmāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:56.868527
  last_modified_at: 2022-03-02 00:08:56.868531
