id: ABC86DC55
title: CXV_§281. drug sde’i miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.986599
  last_modified_at: 2022-03-02 00:08:58.986604
