id: ABC86DC55
title: CI_§8. catvāri tathāgatasya vaiśāradyāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.289701
  last_modified_at: 2022-03-02 00:08:57.289706
