id: ABC86DC55
title: CVIII_§144. paṇḍitaparyāyanāmāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.316767
  last_modified_at: 2022-03-02 00:08:57.316771
