id: ABC86DC55
title: CV_§92. daśakuśalāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.721998
  last_modified_at: 2022-03-02 00:08:57.722016
