id: ABC86DC55
title: CVII_§122. pañcānantarīyāṇi
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.389276
  last_modified_at: 2022-03-02 00:08:57.389280
