id: ABC86DC55
title: CXI_§210. vyā ka ra ṇa’i skad kyi miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.919194
  last_modified_at: 2022-03-02 00:08:58.919199
