id: ABC86DC55
title: CII_§35. catvāri saṃgrahavastūni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:56.941133
  last_modified_at: 2022-03-02 00:08:56.941151
