id: ABC86DC55
title: CVI_§104. caitasikadharmāḥ
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.602538
  last_modified_at: 2022-03-02 00:08:57.602545
