id: ABC86DC55
title: CIII_§55. nirvedhabhagakramaḥ
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:56.827106
  last_modified_at: 2022-03-02 00:08:56.827111
