id: ABC86DC55
title: CVI_§106. dvādaśāyatanāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.610119
  last_modified_at: 2022-03-02 00:08:57.610125
