id: ABC86DC55
title: CXIII_§255. bslab pa bca’ ba’i phan yon bcu daṅ ltuṅ byed sde lṅa la sogs pa’i
  miṅ las phan yon bcu’i miṅ las
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.293089
  last_modified_at: 2022-03-02 00:08:58.293098
