id: ABC86DC55
title: CII_§24. bodhisatvasamādhayaḥ
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:56.871028
  last_modified_at: 2022-03-02 00:08:56.871031
