id: ABC86DC55
title: CI_§18. aśīty anuvyañjanāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.213912
  last_modified_at: 2022-03-02 00:08:57.213919
