id: ABC86DC55
title: CIX_§172. asurā yathā
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.112825
  last_modified_at: 2022-03-02 00:08:57.112828
