id: ABC86DC55
title: CII_§26. bodhisattvabalāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:56.879703
  last_modified_at: 2022-03-02 00:08:56.879708
