id: ABC86DC55
title: CIV_§68. samāpattināmāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.025238
  last_modified_at: 2022-03-02 00:08:57.025241
