id: ABC86DC55
title: CXIV_§272. dge sbyod gi yo byad kyi miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.765794
  last_modified_at: 2022-03-02 00:08:58.765802
