id: ABC86DC55
title: CXIV_§274. sde pa bżi rnam pa
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.785790
  last_modified_at: 2022-03-02 00:08:58.785796
