id: ABC86DC55
title: CXIV_§275. gżi bcu bdun la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.791217
  last_modified_at: 2022-03-02 00:08:58.791223
