id: ABC86DC55
title: CV_ยง95A
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.737125
  last_modified_at: 2022-03-02 00:08:57.737129
