id: ABC86DC55
title: CXIII_§241. puṣpanāmāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.797533
  last_modified_at: 2022-03-02 00:08:57.797554
