id: ABC86DC55
title: CXIV_§264. chad pas bcad ciṅ gso ba la sogs pa’i miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.669549
  last_modified_at: 2022-03-02 00:08:58.669553
