id: ABC86DC55
title: CII_§37. aṣṭadaśaśūnyatā
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:56.948985
  last_modified_at: 2022-03-02 00:08:56.948990
