id: ABC86DC55
title: CXIII_§254. digvidignāmāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.288897
  last_modified_at: 2022-03-02 00:08:58.288903
