id: ABC86DC55
title: CIX_§162. gnas gtsaṅ ma’i sa’i miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.056447
  last_modified_at: 2022-03-02 00:08:57.056450
