id: ABC86DC55
title: CX_§190. śarīrāṅgapratyaṅgāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:59.122956
  last_modified_at: 2022-03-02 00:08:59.122963
