id: ABC86DC55
title: CIII_§51. ṣaḍanusmṛtayaḥ
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:56.809562
  last_modified_at: 2022-03-02 00:08:56.809565
