id: ABC86DC55
title: Colophon
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:59.233749
  last_modified_at: 2022-03-02 00:08:59.233754
