id: ABC86DC55
title: CVI_§102. vedanāskandhanāmāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.582384
  last_modified_at: 2022-03-02 00:08:57.582390
