id: ABC86DC55
title: CXII_§235. raṅganāmāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.583849
  last_modified_at: 2022-03-02 00:08:58.583854
