id: ABC86DC55
title: CVIII_§147. krodhākārāḥ
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.333136
  last_modified_at: 2022-03-02 00:08:57.333140
