id: ABC86DC55
title: CIV_§77. catvāri dharmasamādānāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.045043
  last_modified_at: 2022-03-02 00:08:57.045046
