id: ABC86DC55
title: CVII_§127. skyon du brtsi ba’i miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.437150
  last_modified_at: 2022-03-02 00:08:57.437156
