id: ABC86DC55
title: CIII_§45. pratyekabuddhapudgalāḥ
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:56.778646
  last_modified_at: 2022-03-02 00:08:56.778649
