id: ABC86DC55
title: CXII_§238. sarvālaṃkāranāmāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.614873
  last_modified_at: 2022-03-02 00:08:58.614878
