id: ABC86DC55
title: CVIII_§141. tyāgādayaḥ
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.302733
  last_modified_at: 2022-03-02 00:08:57.302738
