id: ABC86DC55
title: CXI_§219. rol mo byed pa daṅ spyad kyi miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.980112
  last_modified_at: 2022-03-02 00:08:58.980116
