id: ABC86DC55
title: CXII_§221. gar thabs kyi rnams graṅs la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.352147
  last_modified_at: 2022-03-02 00:08:58.352151
