id: ABC86DC55
title: CXIV_§262. bslab pa’i chos maṅ po’i miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.656598
  last_modified_at: 2022-03-02 00:08:58.656604
