id: ABC86DC55
title: CXII_§225. svargakāmādīnām nāmāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.446606
  last_modified_at: 2022-03-02 00:08:58.446612
