id: ABC86DC55
title: CXII_§223. bram ze’i las rnam pa drug gi miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.360612
  last_modified_at: 2022-03-02 00:08:58.360616
