id: ABC86DC55
title: CIV_§75. trividhāḥ prajñāḥ
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.040762
  last_modified_at: 2022-03-02 00:08:57.040764
