id: ABC86DC55
title: CVI_§101. catvāri mahābhūtāni; rūpaskandhanāmāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.579663
  last_modified_at: 2022-03-02 00:08:57.579670
