id: ABC86DC55
title: CXI_§207. caturdaśāvyākṛtamūlāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.900262
  last_modified_at: 2022-03-02 00:08:58.900265
