id: ABC86DC55
title: CXI_§203. spyod pa can gyi gźuṅ la ’byuṅ ba
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.869611
  last_modified_at: 2022-03-02 00:08:58.869615
