id: ABC86DC55
title: CV_§96. śaraṇaparyāyāḥ
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.743082
  last_modified_at: 2022-03-02 00:08:57.743089
