id: ABC86DC55
title: CVIII_§157. ’dod pa’i khams kyi lha’i miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:57.373676
  last_modified_at: 2022-03-02 00:08:57.373683
