id: ABC86DC55
title: CXII_§229. ’bru sna tshogs kyi miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.508574
  last_modified_at: 2022-03-02 00:08:58.508579
