id: ABC86DC55
title: CXII_§237. śaṅkhādināmāni
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.601937
  last_modified_at: 2022-03-02 00:08:58.601942
