id: ABC86DC55
title: CX_§191. lus su ’gyur ba’i rim pa’i miṅ la
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:59.132476
  last_modified_at: 2022-03-02 00:08:59.132482
