id: ABC86DC55
title: CXIII_§260I. navamaṃ daśakam
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-02 00:08:58.348734
  last_modified_at: 2022-03-02 00:08:58.348738
